# Description:
#   Responds with a Homer Simpson "Mmm..." quote anytime a phrase has 3 or more consecutive m's
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   mmm(3+) - triggers a random Homer Simpson "Mmm..." quote
#
# Author:
#   macklinu

quotes = [
  "Mmm... marshmallows.",
  "Mmm... cupcakes.",
  "Mmm... chocolate.",
  "Mmm... double chocolate. (gasp) New flavor, triple chocolate!",
  "Mmm... beer.",
  "Mmm... maca-ma-damia nuts.",
  "Mmm... horse-doovers.",
  "Mmm... pancakes.",
  "Mmm... money.",
  "Mmm... barbecue.",
  "Mmm... purple.",
  "Mmm... sprinkles.",
  "Mmm... spaghetti.",
  "Mmm... beer.",
  "Mmm... salty.",
  "Mmm... the Land of Chocolate.",
  "Mmm... chocolate.",
  "Mmm... crumbled-up cookie things.",
  "Mmm... strained peas.",
  "Mmm... donuts.",
  "Mmm... potato chips.",
  "Mmm... snouts.",
  "Mmm... fattening.",
  "Mmm... burger.",
  "Mmm... Soylent Green.",
  "Mmm... shrimp.",
  "Mmm... hog fat.",
  "Mmm... ham.",
  "Mmm... chicken",
  "Mmm... grapefruit.",
  "Mmm... Gummi Beers",
  "Mmm... organized crime.",
  "Mmm... chocolate.",
  "Mmm... nuts.",
  "Mmm... beer.",
  "Mmm... pie.",
  "Mmm... delicious. Death to America. by Santa",
  "Mmm... 64 slices of American cheese",
  "Mmm... forbidden donut.",
  "Mmm... business deal.",
  "Mmm... invisible cola.",
  "Mmm... candy.",
  "Mmm... convenient.",
  "Mmm... free goo.",
  "Mmm... apple.",
  "Mmm... hamburger.",
  "Mmm... Marge.",
  "Mmm... foot long chili dog. (Homer & Mindy)",
  "Mmm... mediciney.",
  "Mmm... sacrilicious.",
  "Mmm... elephant fresh.",
  "Mmm... caramel.",
  "Mmm... chocolate.",
  "Mmm... invisible cola.",
  "Mmm... forbidden donut.",
  "Mmm... sacrilicious.",
  "Mmm... snouts.",
  "Mmm... free goo.",
  "Mmm... something.",
  "Mmm... bowling fresh.",
  "Mmm... urinal fresh.",
  "Mmm... slanty.",
  "Mmm... beer nuts.",
  "Mmm... incapacitating.",
  "Mmm... unprocessed fishsticks.",
  "Mmm... sprinkles.",
  "Mmm... open-faced club sandwich.",
  "Mmm... pointy.",
  "Mmm... re-circulated air.",
  "Mmm... Homer. [uttered by giant donut in Homer's dream]",
  "Mmm... donuts.",
  "Mmm... memo.",
  "Mmm... me.",
  "Mmm... loganberry.",
  "Mmm... hippo.",
  "Mmm... split peas with ham.",
  "Mmm... fifty-dollar pretzel.",
  "Mmm... ovulicious.",
  "Mmm... Danish.",
  "Mmm... sugar walls.",
  "Mmm... fish.",
  "Mmm... donuts.",
  "Mmm... hug.",
  "Mmm... turbulent.",
  "Mmm... various eggs.",
  "Mmm... unexplained bacon.",
  "Mmm... pistol whip.",
  "Mmm... curds.",
  "Mmm... caramel bologna.",
  "Mmm... pie pants.",
  "Mmm... donuts.",
  "Mmm... feed.",
  "Mmm... steamed gentile.",
  "Mmm... trophy.",
  "Mmm... McNuggets.",
  "Mmm... farfetched.",
  "Mmm... promo.",
  "Mmm... bad eggs.",
  "Mmm... Moses.",
  "Mmm... blowholes.",
  "Mmm... bacon.",
  "Mmm... dumpster buns.",
  "Mmm... Soggy Bread.",
  "Mmm... Homer-oats.",
  "Mmm... Snickers Pie.",
  "Mmm... soggy, smoky hero.",
  "Mmm... developed by.",
  "Mmm... pork pie.",
  "Mmm... pickle.",
  "Mmm... terrible.",
  "Mmm... historically inaccurate.",
  "Mmm... melon-collie.",
  "Mmm... mayo.",
  "Mmm... white chocolate.",
  "Mmm... freedom fries."
]

module.exports = (robot) ->
  robot.hear /(\m)\1\1/i, (msg) ->
    msg.send msg.random quotes
